### PR TITLE
Changing the split regex of paramsText to not ignore Map<String, dynamic>? and required types

### PR DESCRIPTION
**Pull request by luanbatistadev**

### CODE REVIEW

**Comment by davidsdearaujo** [comment]
Hello @luanbatistadev thanks for contributing!

Your regex works nice to your example but still doesn't work for more complex parameters like this one: 
```dart
Map<String, List<Map<String, String>>>
```

To fix that we have created a package that resolves any nested generics types: [fake_reflection](https://pub.dev/packages/fake_reflection)

It would be nice if you could implement the **fake_reflection** instead of using your regex.

**Comment by luanbatistadev** [comment]
I will work on it @davidsdearaujo

**Comment by luanbatistadev** [comment]
@davidsdearaujo would it be interesting to use your package or bring it to the auto_injector(copy)?

**Comment by luanbatistadev** [comment]
@davidsdearaujo  in fake_refection you have to do the tokenization, however it is private, i need to tokenize because the constructorString is a String

**Comment by luanbatistadev** [comment]
Screenshot 2023-08-21 at 15 08 15

**Comment by davidsdearaujo** [comment]
> [**luanbatistadev**](https://github.com/luanbatistadev)
> @davidsdearaujo in fake_refection you have to do the tokenization, however it is private, i need to tokenize because the constructorString is a String

> [**luanbatistadev**](https://github.com/luanbatistadev)
> @davidsdearaujo in fake_refection you have to do the tokenization, however it is private, i need to tokenize because the constructorString is a String

> Screenshot 2023-08-21 at 15 08 15

As we discussed on Discord, we ar gonna keep the **fake_reflection** responsible for parsing the class constructor.

**Comment by davidsdearaujo** [comment]
Fixed on:
- #11

**Pull request closed without merging**
